name: 'Ionic Framework'

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm install
    - name: Build Core
      run: npm run build -- --ci


  test-core-clean-build:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - name: Checking clean build
      run: git diff --exit-code

  test-core-lint:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - run: npm run lint
