name: 'Ionic Framework'

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm install
    - name: Build Core
      run: npm run build -- --ci


  test-core-clean-build:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - name: Checking clean build
      run: git diff --exit-code

  test-core-lint:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - run: npm run lint

  test-core-spec:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - run: npm run test.spec --ci

  test-core-treeshake:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './core/node_modules'
        key: ${{ runner.os }}-core-${{ hashFiles('./core/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-core-
          ${{ runner.os }}-

    - run: npm run test.treeshake --ci



  build-vue:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/vue
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './packages/vue/node_modules'
        key: ${{ runner.os }}-vue-${{ hashFiles('./packages/vue/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-vue-
          ${{ runner.os }}-

    - run: npm install
    - run: ls && sudo npm link
      working-directory: ./core
    - run: sudo npm link @ionic/core
    - run: npm run build

  build-vue-router:
    needs: [build-core, build-vue]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/vue-router
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: './packages/vue-router/node_modules'
        key: ${{ runner.os }}-vue-router-${{ hashFiles('./packages/vue-router/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-vue-router-
          ${{ runner.os }}-

    - run: npm install
    - run: sudo npm link
      working-directory: ./core
    - run: sudo npm link @ionic/core
    - run: sudo npm link
      working-directory: ./packages/vue
    - run: sudo npm link @ionic/vue
    - run: npm run build
