name: 'Ionic Framework'

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
      run: npm run build -- --ci
      working-directory: core
    - name: Restore Dependency Cache
      uses: actions/cache@v2
      with:
        path: |
          './core/node_modules'
          './core/.stencil'
        key: ${{ runner.os }}-core-${{ hashFiles('**/lockfiles') }}

  test-core-clean-build:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - name: Restore Dependency Cache
      uses: actions/cache@v2
      with:
        path: |
          './core/node_modules'
          './core/.stencil'
        key: ${{ runner.os }}-core-${{ hashFiles('**/lockfiles') }}
    - name: Checking clean build
      run: git diff --exit-code

  test-core-lint:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - name: Restore Dependency Cache
      uses: actions/cache@v2
      with:
        path: |
          './core/node_modules'
          './core/.stencil'
        key: ${{ runner.os }}-core-${{ hashFiles('**/lockfiles') }}
    - run: npm run lint
