name: 'Ionic Framework'

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build Core
      run: npm run build -- --ci
    - uses: ionic/cache@v1

  test-core-clean-build:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: ionic/cache@v1
    - name: Checking clean build
      run: git diff --exit-code

  test-core-lint:
    needs: [build-core]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: ionic/cache@v1
    - run: npm run lint
